INSERT INTO public.discount (discount, discount_type, name) VALUES (25.00, 'RATE_BASED', '%25');
INSERT INTO public.discount ( discount, discount_type, name) VALUES (50.00, 'AMOUNT_BASED', '50 dollar');

INSERT INTO public.category ( name) VALUES ('Termite Control');
INSERT INTO public.category ( name) VALUES ('Drywall & Acoustical (FED)');
INSERT INTO public.category ( name) VALUES ('Plumbing & Medical Gas');
INSERT INTO public.category ( name) VALUES ('Doors, Frames & Hardware');
INSERT INTO public.category ( name) VALUES ('Site Furnishings');
INSERT INTO public.category ( name) VALUES ('Soft Flooring and Base');
INSERT INTO public.category ( name) VALUES ('Overhead Doors');
INSERT INTO public.category ( name) VALUES ('Sitework & Site Utilities');
INSERT INTO public.category ( name) VALUES ('Drywall & Acoustical (FED)');
INSERT INTO public.category ( name) VALUES ( 'EIFS');
INSERT INTO public.category ( name) VALUES ( 'Glass & Glazing');
INSERT INTO public.category ( name) VALUES ( 'Structural & Misc Steel Erection');
INSERT INTO public.category ( name) VALUES ( 'Fire Protection');
INSERT INTO public.category ( name) VALUES ( 'Site Furnishings');
INSERT INTO public.category ( name) VALUES ( 'Structural & Misc Steel Erection');
INSERT INTO public.category ( name) VALUES ( 'Sitework & Site Utilities');
INSERT INTO public.category ( name) VALUES ( 'Marlite Panels (FED)');
INSERT INTO public.category ( name) VALUES ( 'Electrical');
INSERT INTO public.category ( name) VALUES ( 'Elevator');
INSERT INTO public.category ( name) VALUES ( 'Framing (Wood)');
INSERT INTO public.category ( name) VALUES ( 'Prefabricated Aluminum Metal Canopies');
INSERT INTO public.category ( name) VALUES ( 'Retaining Wall and Brick Pavers');
INSERT INTO public.category ( name) VALUES ( 'Construction Clean and Final Clean');
INSERT INTO public.category ( name) VALUES ( 'Epoxy Flooring');
INSERT INTO public.category ( name) VALUES ( 'Overhead Doors');
INSERT INTO public.category ( name) VALUES ( 'Retaining Wall and Brick Pavers');
INSERT INTO public.category ( name) VALUES ( 'Structural and Misc Steel (Fabrication)');
INSERT INTO public.category ( name) VALUES ( 'Drywall & Acoustical (MOB)');
INSERT INTO public.category ( name) VALUES ( 'Ornamental Railings');
INSERT INTO public.category ( name) VALUES ( 'Marlite Panels (FED)');
INSERT INTO public.category ( name) VALUES ( 'Termite Control');
INSERT INTO public.category ( name) VALUES ( 'Prefabricated Aluminum Metal Canopies');
INSERT INTO public.category ( name) VALUES ( 'Elevator');
INSERT INTO public.category ( name) VALUES ( 'Temp Fencing, Decorative Fencing and Gates');
INSERT INTO public.category ( name) VALUES ( 'Electrical and Fire Alarm');
INSERT INTO public.category ( name) VALUES ( 'Waterproofing & Caulking');
INSERT INTO public.category ( name) VALUES ( 'Wall Protection');
INSERT INTO public.category ( name) VALUES ( 'EIFS');
INSERT INTO public.category ( name) VALUES ( 'Temp Fencing, Decorative Fencing and Gates');
INSERT INTO public.category ( name) VALUES ( 'Granite Surfaces');
INSERT INTO public.category ( name) VALUES ( 'Fire Protection');
INSERT INTO public.category ( name) VALUES ( 'Elevator');
INSERT INTO public.category ( name) VALUES ( 'Retaining Wall and Brick Pavers');
INSERT INTO public.category ( name) VALUES ( 'Structural & Misc Steel Erection');
INSERT INTO public.category ( name) VALUES ( 'EIFS');
INSERT INTO public.category ( name) VALUES ( 'Plumbing & Medical Gas');
INSERT INTO public.category ( name) VALUES ( 'Asphalt Paving');
INSERT INTO public.category ( name) VALUES ( 'Drywall & Acoustical (MOB)');
INSERT INTO public.category ( name) VALUES ( 'HVAC');
INSERT INTO public.category ( name) VALUES ( 'Structural & Misc Steel Erection');


INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('asturton0@list-manage.com', 'Anstice', 'Sturton', 'asturton0');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('cmulqueeny1@networkadvertising.org', 'Cobby', 'Mulqueeny', 'cmulqueeny1');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('bmaccaughey2@wufoo.com', 'Bell', 'MacCaughey', 'bmaccaughey2');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('mbullivant3@behance.net', 'Maribelle', 'Bullivant', 'mbullivant3');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('cpagitt4@slate.com', 'Casie', 'Pagitt', 'cpagitt4');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('nmonck5@webnode.com', 'Nance', 'Monck', 'nmonck5');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('mokinneally6@zimbio.com', 'Moina', 'O''Kinneally', 'mokinneally6');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('dpetchell7@oracle.com', 'Danny', 'Petchell', 'dpetchell7');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('jrosenau8@dagondesign.com', 'Janela', 'Rosenau', 'jrosenau8');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ( 'ahammerich9@deliciousdays.com', 'Arley', 'Hammerich', 'ahammerich9');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('tsicklinga@4shared.com', 'Tilda', 'Sickling', 'tsicklinga');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('cbevissb@godaddy.com', 'Clyve', 'Beviss', 'cbevissb');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('kfedorskic@berkeley.edu', 'Krystyna', 'Fedorski', 'kfedorskic');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('mrummingsd@uiuc.edu', 'Marylynne', 'Rummings', 'mrummingsd');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('gknighte@bbb.org', 'Glennie', 'Knight', 'gknighte');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('lbynethf@infoseek.co.jp', 'Lutero', 'Byneth', 'lbynethf');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('aapplegarthg@nymag.com', 'Alma', 'Applegarth', 'aapplegarthg');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('twemmh@feedburner.com', 'Therese', 'Wemm', 'twemmh');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('cantonognolii@sciencedaily.com', 'Cayla', 'Antonognoli', 'cantonognolii');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('dcoplestonej@privacy.gov.au', 'Dodi', 'Coplestone', 'dcoplestonej');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('ctimlink@dailymail.co.uk', 'Caralie', 'Timlin', 'ctimlink');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('apaverl@ox.ac.uk', 'Axe', 'Paver', 'apaverl');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('fbeminsterm@yahoo.co.jp', 'Flem', 'Beminster', 'fbeminsterm');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('aredwoodn@elegantthemes.com', 'Arne', 'Redwood', 'aredwoodn');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('kkervino@miitbeian.gov.cn', 'Katina', 'Kervin', 'kkervino');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('tcoolahanp@dailymotion.com', 'Tam', 'Coolahan', 'tcoolahanp');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('kconrathq@indiegogo.com', 'Keelby', 'Conrath', 'kconrathq');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('ephebyr@bloglines.com', 'Ernaline', 'Pheby', 'ephebyr');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('mkasmans@ucsd.edu', 'Malissia', 'Kasman', 'mkasmans');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('bcanett@typepad.com', 'Bryn', 'Canet', 'bcanett');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('minmettu@psu.edu', 'Marmaduke', 'Inmett', 'minmettu');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('obritneyv@bravesites.com', 'Olwen', 'Britney', 'obritneyv');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('omaww@free.fr', 'Olympie', 'Maw', 'omaww');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('kmeesex@nhs.uk', 'Kerr', 'Meese', 'kmeesex');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('nmuldowneyy@ucla.edu', 'Nichol', 'Muldowney', 'nmuldowneyy');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('smacclintonz@spotify.com', 'Shae', 'MacClinton', 'smacclintonz');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('wjindacek10@weather.com', 'Wye', 'Jindacek', 'wjindacek10');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('dmalone11@smh.com.au', 'Dix', 'Malone', 'dmalone11');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('rcaseri12@cbsnews.com', 'Rafaellle', 'Caseri', 'rcaseri12');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('tcaddell13@spotify.com', 'Tricia', 'Caddell', 'tcaddell13');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('dtyas14@canalblog.com', 'Dawn', 'Tyas', 'dtyas14');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('cperrett15@domainmarket.com', 'Carole', 'Perrett', 'cperrett15');
INSERT INTO public.customer ( email, first_name, last_name, user_name) VALUES ('tmcgloughlin16@pinterest.com', 'Tracee', 'McGloughlin', 'tmcgloughlin16');